Add minimal test for truncated links, also improving testsuite run script

diff --git a/4dSYM/testsuite/scalar/run_tests b/4dSYM/testsuite/scalar/run_tests
--- a/4dSYM/testsuite/scalar/run_tests
+++ b/4dSYM/testsuite/scalar/run_tests
@@ -6,9 +6,43 @@ if [ $# -gt 1 ]; then
   N=$1
   target=$2
 
+  # Special case with truncated links
+  # Run `./run_tests SU2 hmc`
+  # Apart from setting up defines.h, follows same steps as documented below
+  if [ $N = 'SU2' ]; then
+    cd ../../susy/
+    sed -i -E "s/\/\/(#define TRUNCATED)/\1/" defines.h
+    sed -i -E "s/\/\/(#define EIG_POT)/\1/" defines.h
+
+    echo "Compiling susy_$target..."
+    if ! make -f Make_scalar susy_$target >& /dev/null ; then
+      echo "ERROR: susy_$target compilation failed"
+      make -f Make_scalar susy_$target
+      exit
+    fi
+    sed -i -E "s/(#define TRUNCATED)/\/\/\1/" defines.h
+    sed -i -E "s/(#define EIG_POT)/\/\/\1/" defines.h
+
+    cd ../testsuite/
+    rm -f scalar/$target.SU2.out
+    echo "Running susy_$target..."
+    ../susy/susy_$target < in.SU2.$target > scalar/$target.SU2.out
+
+    cd scalar/
+    d="`diff -I'Time' -I'time' -I'seconds' -I'^start' $target.SU2.ref $target.SU2.out`"
+    if [ -n "$d" ] ; then   # Non-zero string length
+      echo "$target.SU2.ref and $target.SU2.out differ:"
+      echo "$d"
+    else
+      echo "PASS: susy_$target reproduces reference output"
+    fi
+    exit
+  fi
+
+  # Standard case
   # Change N
   cd ../../susy/
-  awk -v"X=#define NCOL $N" '{sub(/^#define NCOL .*/,X);print}' ../include/susy.h > TEMP && mv TEMP ../include/susy.h
+  sed -i -E "s/(#define NCOL) .*/\1 $N/" ../include/susy.h
 
   # Compile
   echo "Compiling susy_$target..."
@@ -19,8 +53,7 @@ if [ $# -gt 1 ]; then
   fi
 
   # Reset to N=2
-  cd ../include/
-  awk -v"X=#define NCOL 2" '{sub(/^#define NCOL .*/,X);print}' susy.h > TEMP && mv TEMP susy.h
+  sed -i -E "s/(#define NCOL) .*/\1 2/" ../include/susy.h
 
   # Run
   cd ../testsuite/
@@ -45,10 +78,11 @@ fi
 for N in 2 3 4 ; do
   echo "N=$N"
 
-  # Compile
-  cd ../../susy/
   # Change N
-  awk -v"X=#define NCOL $N" '{sub(/^#define NCOL .*/,X);print}' ../include/susy.h > TEMP && mv TEMP ../include/susy.h
+  cd ../../susy/
+  sed -i -E "s/(#define NCOL) .*/\1 $N/" ../include/susy.h
+
+  # Compile all targets
   for target in hmc meas hmc_meas mcrg eig cheb mode phase ; do
     echo "Compiling susy_$target..."
     if ! make -f Make_scalar susy_$target >& /dev/null ; then
@@ -57,9 +91,9 @@ for N in 2 3 4 ; do
       exit
     fi
   done
+
   # Reset to N=2
-  cd ../include/
-  awk -v"X=#define NCOL 2" '{sub(/^#define NCOL .*/,X);print}' susy.h > TEMP && mv TEMP susy.h
+  sed -i -E "s/(#define NCOL) .*/\1 2/" ../include/susy.h
 
   # Run
   cd ../testsuite/
@@ -71,15 +105,14 @@ for N in 2 3 4 ; do
 
   # Checkpointed pfaffian computation
   rm -f scalar/phase_part1.U$N.out scalar/phase_part2.U$N.out
-  cp in.U$N.phase SAV
-  awk -v"X=ckpt_save 256" '{sub(/ckpt_save 0/,X);print}' in.U$N.phase > TEMP && mv TEMP in.U$N.phase
+  sed -i -E "s/(ckpt_save) 0/\1 256/" in.U$N.phase
   echo "Running checkpointed susy_phase part 1 of 2..."
   ../susy/susy_phase < in.U$N.phase > scalar/phase_part1.U$N.out
-  cp SAV in.U$N.phase
-  awk -v"X=ckpt_load 256" '{sub(/ckpt_load 0/,X);print}' in.U$N.phase > TEMP && mv TEMP in.U$N.phase
+  sed -i -E "s/(ckpt_load) 0/\1 256/" in.U$N.phase
+  sed -i -E "s/(ckpt_save) 256/\1 0/" in.U$N.phase
   echo "Running checkpointed susy_phase part 2 of 2..."
   ../susy/susy_phase < in.U$N.phase > scalar/phase_part2.U$N.out
-  mv SAV in.U$N.phase
+  sed -i -E "s/(ckpt_load) 256/\1 0/" in.U$N.phase
   rm -f config.U$N.2222.diag256 config.U$N.2222.Q256
 
   # Check
